### ISSUE TITLE
Initial "on air" testing

### ISSUE THREAD

**Issue by N6RFM** [f4gkr/PicTalk#29]
Hi Sylvain,

Thanks so much for creating this updated version!   Able to compile and run the new version under Mint 21.1, which uses Ubuntu 22.04 as the base.

Unable to compile using Mint 20.3, based on Ubuntu 20.4, despite doing an altinstall of python 3.10.      

Just had an overhead pass.  The new version detects the telemetry, but unfortunately no decodes were obtained.   A screenshot is attached.  Please let me know how I may help further.

As an aside, the new version did not compile using Mint 20.3, based on Ubuntu 20.4, despite doing an altinstall of python 3.10.  The process proceeds for some time, and then an error is received.      

/usr/bin/ld: /usr/local/lib/libpython3.10.a(dynload_shlib.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:875: bin/pictalk] Error 1

Perhaps a libray linkage issue, but I do not know how to fix that.  Anyway, will focus on the new version under Ubuntu 22.04 for now.  

Merci,
Bob
N6RFM

![Selection_001](https://user-images.githubusercontent.com/36707700/235312815-8b6dce63-c84b-4a05-99df-ab900323929e.png)

**Comment by f4gkr** [comment]
Bob,

Can you estimate the signal to noise ratio yoy had during this pass ?

I am trying to understand if the issue is in the UI or in the python
decoder.

Sylvain

**Comment by N6RFM** [comment]
Hi Sylvain,Guesstimate is 20-30 dB above noise level.  Direct overhead pass.  Very strong.  What I observed is the signal sync light changing from red to green for each frame , but no decodes printed or uploaded.  Thanks. Bob M.On Apr 29, 2023, at 14:29, Sylvain AZARIAN ***@***.***> wrote:﻿
Bob,

Can you estimate the signal to noise ratio yoy had during this pass ?

I am trying to understand if the issue is in the UI or in the python
decoder.

Sylvain

**Comment by f4gkr** [comment]
Bonjour

Ok... so it should have been decoded with such a value. Do you have any IQ
recording ? My sat setup is currently down....

Sylvain

**Comment by N6RFM** [comment]
Bonjour,   I will make one in a few hours when there is a high pass here.  Bob M.On Apr 30, 2023, at 07:19, Sylvain AZARIAN ***@***.***> wrote:﻿
Bonjour

Ok... so it should have been decoded with such a value. Do you have any IQ
recording ? My sat setup is currently down....

Sylvain

**Comment by N6RFM** [comment]
Bonjour Sylvain,

Two (sequential IQ) files are uploaded here -
https://mega.nz/folder/f91U3Q7a#21uYhIdynMRU50zlhvh49Q
The signal strength for some of the strongest frames was > 25 dB over
baseline.  Good decodes using a UZ7HO G3RUH BPSK modem.

The files were made using SDRConsole (a Windows application)
Soxi indicates
***@***.***:~/Desktop/PicSat_test$ soxi 30-Apr-2023\ 231604.988\ 435.525MHz\
000.wav

Input File     : '30-Apr-2023 231604.988 435.525MHz 000.wav'
Channels       : 2
Sample Rate    : 625000
Precision      : 16-bit
Duration       : 00:06:40.00 = 250000000 samples ~ 30000 CDDA sectors
File Size      : 1.00G
Bit Rate       : 20.0M
Sample Encoding: 16-bit Signed Integer PCM

73 es tks,
Bob

**Comment by f6bvp** [comment]
Hi Sylvain,
Congrats for now PicTalk compiles well on Ubuntu 22.04 and Python 3.10.7 and runs fine.

Displayed version is v 1.1  27-02-18

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Found Rafael Micro R820T tuner
 Tuner type: 5  min_tuner_freq= 24000000  max_tuner_freq= 1766000000
 gain range :  0  to  49.6
 manufacturer :: Realtek
 product :: RTL2838UHIDIR
 serial :: 00000001
Exact sample rate is: 2200000,014570 Hz
Web server listening on port 8001
Controller::run() 
transition from  0  to  1
using Python : "/usr/local/src/PicTalk/bin/python/decodeZ3.py"
starting PythonDecoder::run()
starting python

Starting ZMQ publisher…
Started ZMQ publisher.
Connecting to PicTalk
Connected to PicTalk.
Starting Main Thread
Controller::run()  ends


There are still a few warnings about deprecated stuff like :
mainwindow.cpp: In constructor ‘MainWindow::MainWindow(QWidget*)’:
mainwindow.cpp:158:33: warning: ‘QPalette::Background’ is deprecated: Use QPalette::Window instead [-Wdeprecated-declarations]
  158 |     zpalette.setColor( zpalette.Background, QColor(0, 170, 255));
      |                                 ^~~~~~~~~~
and Unused parameters  like : 
i/bookmarks.cpp: In member function ‘QList<BookmarkInfo> Bookmarks::getBookmarksInRange(qint64, qint64, float)’:
ui/bookmarks.cpp:229:83: warning: unused parameter ‘maxDistance’ [-Wunused-parameter]
  229 | QList<BookmarkInfo> Bookmarks::getBookmarksInRange(qint64 low, qint64 high, float maxDistance)
      |                                                                             ~~~~~~^~~~~~~~~~~
and :
dsp/frameprocessor.cpp: In member function ‘int FrameProcessor::processDataAD(tSComplex*, int, int)’:
dsp/frameprocessor.cpp:188:24: warning: this statement may fall through [-Wimplicit-fallthrough=]
  188 |             next_state = sSearchFrame ;
      |             ~~~~~~~~~~~^~~~~~~~~~~~~~
dsp/frameprocessor.cpp:191:9: note: here
  191 |         case sSearchFrame:
      |         ^~~~

and : 
e/airspy/airspy.c
hardware/airspy/airspy.c: In function ‘airspy_set_linearity_gain’:
hardware/airspy/airspy.c:1766:32: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1766 |                 else if (value < 0)
      |                                ^
hardware/airspy/airspy.c: In function ‘airspy_set_sensitivity_gain’:
hardware/airspy/airspy.c:1803:32: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1803 |                 else if (value < 0)
      |                                ^
hardware/airspy/airspy.c: At top level:
hardware/airspy/airspy.c:106:19: warning: ‘str_product_airspy’ defined but not used [-Wunused-const-variable=]
  106 | static const char str_product_airspy[STR_PRODUCT_AIRSPY_SIZE] =
      |                   ^~~~~~~~~~~~~~~~~~
hardware/airspy/airspy.c: In function ‘airspy_open_init’:
hardware/airspy/airspy.c:668:82: warning: ‘%s’ directive argument is not a nul-terminated string [-Wformat-overflow=]
  668 |                                                 sprintf(serial_number_expected, "%s%08X%08X",
      |                                                                                  ^~
  669 |                                                         str_prefix_serial_airspy,
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~  
hardware/airspy/airspy.c:110:19: note: referenced argument declared here
  110 | static const char str_prefix_serial_airspy[STR_PREFIX_SERIAL_AIRSPY_SIZE] =
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
![PicTalk-V1 1-27-02-18](https://user-images.githubusercontent.com/14106669/235438107-162fb133-7eaa-41f8-9700-739d487b4850.png)

**Comment by f4gkr** [comment]
Thanks Bernard

Yes, it was a quick and dirty fix and some deprecations were left. Cleaning
this properly will take much longer but I have this on my todo list....

Sylvain

**Comment by f4gkr** [comment]
Thank, I will download the files this afternoon

Sylvain
